apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-egd-rke2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: clusters/egd_rke2
    repoURL: https://github.com/sika-training-examples/2026-02-27_edg-kubernetes-example-final.git
    directory:
      recurse: true
      exclude: '{**/manifests/**,**/Chart.yaml,**/values.y*ml,**/*.values.y*ml,**/templates/**}'

