apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: loki
  destination:
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sika-training-examples/2026-02-27_edg-kubernetes-example-final.git
      path: ./clusters/egd_ocp/_system/loki/manifests
