apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  project: kafka
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sika-training-examples/2026-02-27_edg-kubernetes-example-final.git
      path: ./clusters/egd_ocp/kafka/manifests
