apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-egd-ocp
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-of-apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
  source:
    path: clusters/egd_ocp
    repoURL: https://github.com/sika-training-examples/2026-02-27_edg-kubernetes-example-final.git
    directory:
      recurse: true
      exclude: '{**/manifests/**,**/Chart.yaml,**/values.y*ml,**/*.values.y*ml,**/templates/**,**/values/**}'
